#!/bin/bash

DIR="${1:-.}"
DIR="$(realpath "$DIR")"
DIRNAME="$(basename "$DIR")"
TARGET="/home/zzh1996/$DIRNAME"

docker run --rm -it \
    -v "$DIR:$TARGET" \
    -w "$TARGET" \
    zzh1996/mydocker
